news_site:
  infobae:
    url: https://www.infobae.com
    queries:
      homepage_article_links: '.headline-link'
      article_body: '.paragraph'
      article_title: '.article-headline'
  clarin:
    url: https://www.clarin.com/
    queries:
      homepage_article_links: '.eQzoJk'
      article_body: '.StoryTextContainer'
      article_title: '.storyTitle'
  nacion:
    url: https://www.lanacion.com.ar/
    queries:
      homepage_article_links: '.ln-link'
      article_body: '.com-title'
      article_title: '.com-paragraph'
